on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: write

jobs:
  deployment-step:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            
        - uses: azure/bicep-deploy@v2
          id: bicep-resources-deploy
          with:
            type: deployment
            operation: create
            scope: subscription
            name: main-deploy-yaml-${{ github.run_id }}
            location: eastus2
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            template-file: infra/main.bicep
            parameters-file: infra/main.bicepparam